travis:
  secure:
    BINSTAR_TOKEN: 2cLbcvBWC5Qp+w40GKIyq3lNCHcxMyd5RbGS3YS6uIr38/9xhYumdOhJ4KzTTl+g0O3egsakzCkSCV98Ftq+KtF7kOL9O9ze2AnHI/cgfMd7gFIwiSmtsl7qsv34H4qHi/Pt3anmCj2k/xLqyaoyCeI9zYyyyn4ROlDBEbS8CHvE2a+3xcRKxKuzekb6aoh18xyXipA0xUV6c2nF+/pqSQykapAdKab5nuG3S1M0tNTurduVu+9q53ea88KEnxWjxmJF2Jp4jJ6JEOKVDDUHJMOvBrVanrqM/BrnMJc85yUYGxliZL//yXozB7XLTTKAn89sCagpfNwXzdRwIUrDXHkunUKauHckdzvb5eeF+u4X4gMWY5Bu+xqYhlsdgb0mVy1aKeUqI8WScVwV5qpMsZVygTrOudjW4rERkGDzeHLgYUUw110vh/0SJaRnXyo+L4gKi3Lw6TSUGsBZ52662ZXZpohrnMewjgrb+oUso/P+kHzwP7aVwB1vIKGhTHexJ2Cfg81R/6+R3Oi56V9Vp8anchg+GtKpeUqcM29P+RT3Veu/B1syifH5ASes5YanOvBzafVDsrN0chAEFeml+3xWPSw7bFVY6Ka/biNSmRpq5tqQ6yze2G+qxKmIt4oYwnyztgZdKni3n8KZJ7NFGBrMMxAkeRT3JVhew6lMeW0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
